baseURL = 'https://israchaves.github.io/'
languageCode = 'es-es'
title = 'Sitio personal de Israel Chaves Arbaiza'
theme = 'PaperMod'

# ---------------------------------------------------------
# CONFIGURACIÓN DE PARÁMETROS
# ---------------------------------------------------------
[params]
  # Otros parámetros generales (ej. modo oscuro)
  defaultTheme = "auto"
  
  # 1. Definir la tabla profileMode (Configuración principal)
  [params.profileMode]
    enabled = true
    title = "Israel Chaves"
    subtitle = "Ing. Mecatrónico | Docente e Investigador"
    imageUrl = "images/website_me.jpg"
    imageTitle = "Foto de perfil de Israel Chaves"
    imageWidth = 180
    imageHeight = 240

  # 2. Definir la lista de botones (OJO: Los corchetes dobles [[...]])
  # Esto debe ir DESPUÉS de cerrar la configuración anterior, pero sigue siendo parte de params.profileMode
  [[params.profileMode.buttons]]
    name = "Sobre Mí"
    url = "about/"

  [[params.profileMode.buttons]]
    name = "Ver Cursos"
    url = "cursos/"

  [[params.profileMode.buttons]]
    name = "Descargar CV"
    url = "/docs/cv-israel-chaves-academic.pdf"

  # --- Redes Sociales ---
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/israchaves"
    title = "GitHub"

  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?hl=en&user=a9TAEUgAAAAJ"
    title = "GoogleScholar"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/israchaves"
    title = "LinkedIn"
  
  [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/israchaves.bsky.social"
    title = "Bluesky"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@israchaves"
    title = "Mastodon"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:israel.chaves@ucr.ac.cr"
    title = "Email"

    socialIconsInFooter = true # (Nota: verifica si tu versión de PaperMod soporta esto nativamente)




  # --- Información de Contacto Adicional (Opcional, texto libre) ---
  # PaperMod no tiene un campo nativo para "dirección/teléfono" en el sidebar,
  # pero podemos usar el subtítulo o agregarlo en el contenido de homeInfoParams si quisieras.

# -------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true	# Para que no haya Warnings de render unsafe con mis HTML
# -------------------

[menu]
  [[menu.main]]
    name = "CV"
    url = "/docs/cv-israel-chaves-academic.pdf"
    weight = 10
  [[menu.main]]
    name = "Cursos"
    pageRef = "/cursos"
    weight = 20
  [[menu.main]]
    name = "Publicaciones"
    pageRef = "/publicaciones"
    weight = 30
  [[menu.main]]
    name = "Reserva de consulta"
    pageRef = "/reserva"
    weight = 30
  [[menu.main]]
    name = "Tutoriales"
    pageRef = "/tutoriales"
    weight = 40

# Habilitar etiquetas para los tutoriales
[taxonomies]
  tag = "tags"
